version: '3.4'

services:
  shop.apigateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  shop.productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  shop.basketservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

